### ISSUE TITLE
Bug in game data

### ISSUE THREAD

**Issue by jessebett** [ProbabilisticLearning/Assignment-2#1]
thanks student tianyi!

Below is the first 9 rows of ```games.csv```.
winner,loser
1,2
3,2
2,4
5,2
6,7
8,8
7,9
10,7
7,7

--- Update

I took a close look into ```data_clean.jl``` and found the following issue:
 ```22 # ╔═╡ fed6345e-81f1-11eb-2d6d-75d8179d6f63
 23 function find_result(row)
 24     if row[:white_result] == "win"
 25         return [row[:white_username], row[:black_username]]
 26     elseif row[:black_result] == "win"
 27         return [row[:black_username], row[:black_username]]
 28     else
 29         return nothing
 30     end
 31 end
```
In row 27, I think it should be ```return [row[:black_username], row[:white_username]]``` instead of ```return [row[:black_username], row[:black_username]]```.

**Comment by tianyi21** [comment]
I sent a PR #2 regarding this issue
